ALLEN_RELATIONS = frozenset(
    {
        "before",
        "after",
        "meets",
        "met_by",
        "overlaps",
        "overlapped_by",
        "starts",
        "started_by",
        "during",
        "contains",
        "finishes",
        "finished_by",
        "equals",
    }
)

ALLEN_CONVERSE = {
    "before": "after",
    "after": "before",
    "meets": "met_by",
    "met_by": "meets",
    "overlaps": "overlapped_by",
    "overlapped_by": "overlaps",
    "starts": "started_by",
    "started_by": "starts",
    "during": "contains",
    "contains": "during",
    "finishes": "finished_by",
    "finished_by": "finishes",
    "equals": "equals",
}
ALLEN_COMPOSE = {
    # before (p)
    ("before", "before"): {"before"},
    ("before", "meets"): {"before"},
    ("before", "overlaps"): {"before"},
    ("before", "finished_by"): {"before"},
    ("before", "contains"): {"before"},
    ("before", "starts"): {"before"},
    ("before", "equals"): {"before"},
    ("before", "started_by"): {"before"},
    ("before", "during"): {"before", "meets", "overlaps", "starts", "during"},
    ("before", "finishes"): {"before", "meets", "overlaps", "starts", "during"},
    ("before", "overlapped_by"): {"before", "meets", "overlaps", "starts", "during"},
    ("before", "met_by"): {"before", "meets", "overlaps", "starts", "during"},
    ("before", "after"): {
        "before",
        "meets",
        "overlaps",
        "finished_by",
        "contains",
        "starts",
        "equals",
        "started_by",
        "during",
        "finishes",
        "overlapped_by",
        "met_by",
        "after",
    },
    # meets (m)
    ("meets", "before"): {"before"},
    ("meets", "meets"): {"before"},
    ("meets", "overlaps"): {"before"},
    ("meets", "finished_by"): {"before"},
    ("meets", "contains"): {"before"},
    ("meets", "starts"): {"meets"},
    ("meets", "equals"): {"meets"},
    ("meets", "started_by"): {"meets"},
    ("meets", "during"): {"overlaps", "starts", "during"},
    ("meets", "finishes"): {"overlaps", "starts", "during"},
    ("meets", "overlapped_by"): {"overlaps", "starts", "during"},
    ("meets", "met_by"): {"finished_by", "equals", "finishes"},
    ("meets", "after"): {"contains", "started_by", "overlapped_by", "met_by", "after"},
    # overlaps (o)
    ("overlaps", "before"): {"before"},
    ("overlaps", "meets"): {"before"},
    ("overlaps", "overlaps"): {"before", "meets", "overlaps"},
    ("overlaps", "finished_by"): {"before", "meets", "overlaps"},
    ("overlaps", "contains"): {
        "before",
        "meets",
        "overlaps",
        "finished_by",
        "contains",
    },
    ("overlaps", "starts"): {"overlaps"},
    ("overlaps", "equals"): {"overlaps"},
    ("overlaps", "started_by"): {"overlaps", "finished_by", "contains"},
    ("overlaps", "during"): {"overlaps", "starts", "during"},
    ("overlaps", "finishes"): {"overlaps", "starts", "during"},
    ("overlaps", "overlapped_by"): {
        "overlaps",
        "finished_by",
        "contains",
        "starts",
        "equals",
        "started_by",
        "during",
        "finishes",
        "overlapped_by",
    },
    ("overlaps", "met_by"): {"contains", "started_by", "overlapped_by"},
    ("overlaps", "after"): {
        "contains",
        "started_by",
        "overlapped_by",
        "met_by",
        "after",
    },
    # finished_by (f)
    ("finished_by", "before"): {"before"},
    ("finished_by", "meets"): {"meets"},
    ("finished_by", "overlaps"): {"overlaps"},
    ("finished_by", "finished_by"): {"finished_by"},
    ("finished_by", "contains"): {"contains"},
    ("finished_by", "starts"): {"overlaps"},
    ("finished_by", "equals"): {"finished_by"},
    ("finished_by", "started_by"): {"contains"},
    ("finished_by", "during"): {"overlaps", "starts", "during"},
    ("finished_by", "finishes"): {"finished_by", "equals", "finishes"},
    ("finished_by", "overlapped_by"): {"contains", "started_by", "overlapped_by"},
    ("finished_by", "met_by"): {"contains", "started_by", "overlapped_by"},
    ("finished_by", "after"): {
        "contains",
        "started_by",
        "overlapped_by",
        "met_by",
        "after",
    },
    # contains (c)
    ("contains", "before"): {"before", "meets", "overlaps", "finished_by", "contains"},
    ("contains", "meets"): {"overlaps", "finished_by", "contains"},
    ("contains", "overlaps"): {"overlaps", "finished_by", "contains"},
    ("contains", "finished_by"): {"contains"},
    ("contains", "contains"): {"contains"},
    ("contains", "starts"): {"overlaps", "finished_by", "contains"},
    ("contains", "equals"): {"contains"},
    ("contains", "started_by"): {"contains"},
    ("contains", "during"): {
        "overlaps",
        "finished_by",
        "contains",
        "starts",
        "equals",
        "started_by",
        "during",
        "finishes",
        "overlapped_by",
    },
    ("contains", "finishes"): {"contains", "started_by", "overlapped_by"},
    ("contains", "overlapped_by"): {"contains", "started_by", "overlapped_by"},
    ("contains", "met_by"): {"contains", "started_by", "overlapped_by"},
    ("contains", "after"): {
        "contains",
        "started_by",
        "overlapped_by",
        "met_by",
        "after",
    },
    # starts (s)
    ("starts", "before"): {"before"},
    ("starts", "meets"): {"before"},
    ("starts", "overlaps"): {"before", "meets", "overlaps"},
    ("starts", "finished_by"): {"before", "meets", "overlaps"},
    ("starts", "contains"): {"before", "meets", "overlaps", "finished_by", "contains"},
    ("starts", "starts"): {"starts"},
    ("starts", "equals"): {"starts"},
    ("starts", "started_by"): {"starts", "equals", "started_by"},
    ("starts", "during"): {"during"},
    ("starts", "finishes"): {"during"},
    ("starts", "overlapped_by"): {"during", "finishes", "overlapped_by"},
    ("starts", "met_by"): {"met_by"},
    ("starts", "after"): {"after"},
    # equals (e)
    ("equals", "before"): {"before"},
    ("equals", "meets"): {"meets"},
    ("equals", "overlaps"): {"overlaps"},
    ("equals", "finished_by"): {"finished_by"},
    ("equals", "contains"): {"contains"},
    ("equals", "starts"): {"starts"},
    ("equals", "equals"): {"equals"},
    ("equals", "started_by"): {"started_by"},
    ("equals", "during"): {"during"},
    ("equals", "finishes"): {"finishes"},
    ("equals", "overlapped_by"): {"overlapped_by"},
    ("equals", "met_by"): {"met_by"},
    ("equals", "after"): {"after"},
    # started_by (sb)
    ("started_by", "before"): {
        "before",
        "meets",
        "overlaps",
        "finished_by",
        "contains",
    },
    ("started_by", "meets"): {"overlaps", "finished_by", "contains"},
    ("started_by", "overlaps"): {"overlaps", "finished_by", "contains"},
    ("started_by", "finished_by"): {"contains"},
    ("started_by", "contains"): {"contains"},
    ("started_by", "starts"): {"starts", "equals", "started_by"},
    ("started_by", "equals"): {"started_by"},
    ("started_by", "started_by"): {"started_by"},
    ("started_by", "during"): {"during", "finishes", "overlapped_by"},
    ("started_by", "finishes"): {"overlapped_by"},
    ("started_by", "overlapped_by"): {"overlapped_by"},
    ("started_by", "met_by"): {"met_by"},
    ("started_by", "after"): {"after"},
    # during (d)
    ("during", "before"): {"before"},
    ("during", "meets"): {"before"},
    ("during", "overlaps"): {"before", "meets", "overlaps", "starts", "during"},
    ("during", "finished_by"): {"before", "meets", "overlaps", "starts", "during"},
    ("during", "contains"): {
        "before",
        "meets",
        "overlaps",
        "finished_by",
        "contains",
        "starts",
        "equals",
        "started_by",
        "during",
        "finishes",
        "overlapped_by",
        "met_by",
        "after",
    },
    ("during", "starts"): {"during"},
    ("during", "equals"): {"during"},
    ("during", "started_by"): {
        "during",
        "finishes",
        "overlapped_by",
        "met_by",
        "after",
    },
    ("during", "during"): {"during"},
    ("during", "finishes"): {"during"},
    ("during", "overlapped_by"): {
        "during",
        "finishes",
        "overlapped_by",
        "met_by",
        "after",
    },
    ("during", "met_by"): {"after"},
    ("during", "after"): {"after"},
    # finishes (f)
    ("finishes", "before"): {"before"},
    ("finishes", "meets"): {"meets"},
    ("finishes", "overlaps"): {"overlaps", "starts", "during"},
    ("finishes", "finished_by"): {"finished_by", "equals", "finishes"},
    ("finishes", "contains"): {
        "contains",
        "started_by",
        "overlapped_by",
        "met_by",
        "after",
    },
    ("finishes", "starts"): {"during"},
    ("finishes", "equals"): {"finishes"},
    ("finishes", "started_by"): {"overlapped_by", "met_by", "after"},
    ("finishes", "during"): {"during"},
    ("finishes", "finishes"): {"finishes"},
    ("finishes", "overlapped_by"): {"overlapped_by", "met_by", "after"},
    ("finishes", "met_by"): {"after"},
    ("finishes", "after"): {"after"},
    # overlapped_by (ob)
    ("overlapped_by", "before"): {
        "before",
        "meets",
        "overlaps",
        "finished_by",
        "contains",
    },
    ("overlapped_by", "meets"): {"overlaps", "finished_by", "contains"},
    ("overlapped_by", "overlaps"): {
        "overlaps",
        "finished_by",
        "contains",
        "starts",
        "equals",
        "started_by",
        "during",
        "finishes",
        "overlapped_by",
    },
    ("overlapped_by", "finished_by"): {"contains", "started_by", "overlapped_by"},
    ("overlapped_by", "contains"): {
        "contains",
        "started_by",
        "overlapped_by",
        "met_by",
        "after",
    },
    ("overlapped_by", "starts"): {"during", "finishes", "overlapped_by"},
    ("overlapped_by", "equals"): {"overlapped_by"},
    ("overlapped_by", "started_by"): {"overlapped_by", "met_by", "after"},
    ("overlapped_by", "during"): {"during", "finishes", "overlapped_by"},
    ("overlapped_by", "finishes"): {"overlapped_by"},
    ("overlapped_by", "overlapped_by"): {"overlapped_by", "met_by", "after"},
    ("overlapped_by", "met_by"): {"after"},
    ("overlapped_by", "after"): {"after"},
    # met_by (mb)
    ("met_by", "before"): {"before", "meets", "overlaps", "finished_by", "contains"},
    ("met_by", "meets"): {"starts", "equals", "started_by"},
    ("met_by", "overlaps"): {"during", "finishes", "overlapped_by"},
    ("met_by", "finished_by"): {"met_by"},
    ("met_by", "contains"): {"after"},
    ("met_by", "starts"): {"during", "finishes", "overlapped_by"},
    ("met_by", "equals"): {"met_by"},
    ("met_by", "started_by"): {"after"},
    ("met_by", "during"): {"during", "finishes", "overlapped_by"},
    ("met_by", "finishes"): {"met_by"},
    ("met_by", "overlapped_by"): {"after"},
    ("met_by", "met_by"): {"after"},
    ("met_by", "after"): {"after"},
    # after (a)
    ("after", "before"): {
        "before",
        "meets",
        "overlaps",
        "finished_by",
        "contains",
        "starts",
        "equals",
        "started_by",
        "during",
        "finishes",
        "overlapped_by",
        "met_by",
        "after",
    },
    ("after", "meets"): {"during", "finishes", "overlapped_by", "met_by", "after"},
    ("after", "overlaps"): {"during", "finishes", "overlapped_by", "met_by", "after"},
    ("after", "finished_by"): {"after"},
    ("after", "contains"): {"after"},
    ("after", "starts"): {"during", "finishes", "overlapped_by", "met_by", "after"},
    ("after", "equals"): {"after"},
    ("after", "started_by"): {"after"},
    ("after", "during"): {"during", "finishes", "overlapped_by", "met_by", "after"},
    ("after", "finishes"): {"after"},
    ("after", "overlapped_by"): {"after"},
    ("after", "met_by"): {"after"},
    ("after", "after"): {"after"},
}
